sun-shine0708/freemarket_sample_60b

README.md
- データベース設計
- READMEに記載
#Why
- 本アプリにおける様々な機能実装のため。
=> edit_RaadMe

app/assets/stylesheets/_userspreview.scss, app/assets/stylesheets/application.scss, app/controllers/users_controller.rb, app/views/users/preview.html.haml, config/routes.rb
#what
本人確認画面実装
#why
アプリの機能として必要なため
=> front-function

Gemfile, Gemfile.lock, config/unicorn.rb
=> unicorn-function

config/database.yml
#what
database.yml編集
#why
deploy作業
=> database.yml-function

config/unicorn.rb
#what
unicorn.rb修正
#why
deploy作業のため
=> unicorn-edit

Capfile, Gemfile, Gemfile.lock, config/deploy.rb, config/deploy/production.rb, config/deploy/staging.rb, config/environments/production.rb, config/unicorn.rb
#what
Capistrano実装
#why
deploy作業
=> Capistrano-function

app/controllers/application_controller.rb, config/deploy.rb, config/deploy/production.rb
#what
ベーシック認証実装
#why
deploy作業のため
=> basic-authentication

app/assets/stylesheets/_products.scss, app/views/layouts/_header.html.haml, app/views/products/index.html.haml
トップページヘッダーの修正
link_to/formの追加
より綺麗なviewを作成するため。
=> edit_header_commit

.gitignore
#what
secrets.yml再作成
#why
masterにマージすると削除されてしまったから
=> secrets.yml-function

app/assets/stylesheets/_show.scss, app/models/user.rb, app/views/users/_notification-list.html.haml, app/views/users/_side-bar.html.haml, app/views/users/_todo-list.html.haml, app/views/users/show.html.haml
- マイページのビューの作成・編集
- hoverアクション追加
- uesrモデルのshowアクションに対応するビューが必要なため
=> edit-mypage-action

config/initializers/carrierwave.rb
#what
自動デプロイを行う
#why
自動デプロイするためにcarrierwaveを修正
=> carrierwave-edit

app/controllers/products_controller.rb
#what
productsのnewアクションを作成
#why
ビュー作成のため
=> @products-add

app/views/users/edit.html.haml, app/views/users/preview.html.haml
#what
プロフィール編集画面、本人確認画面にrenderを追加
#why
メルカリ画面と同様にするため
=> render-add

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/_logout.scss, app/assets/stylesheets/users/_side-bar.scss, app/views/users/_side-bar.html.haml, app/views/users/logout.html.haml
=> logbtn-view

app/assets/stylesheets/application.scss, app/assets/stylesheets/users/_mail_password.scss, app/controllers/users_controller.rb, app/views/users/_side-bar.html.haml, app/views/users/mail_password.html.haml, config/routes.rb
=> mail-password-view

app/assets/javascripts/payjp.js, app/assets/stylesheets/devise/registrations/_signup.scss, app/controllers/creditcards_controller.rb, app/controllers/streetaddresses_controller.rb, app/models/creditcard.rb, app/models/streetaddress.rb, app/models/user.rb, app/views/creditcards/new.html.haml, app/views/streetaddresses/new.html.haml, config/routes.rb, db/migrate/20191011122122_remove_card_number_from_creditcards.rb, db/migrate/20191011123115_add_customer_id_to_creditcards.rb, db/schema.rb
#what
pay.jpから情報を取得しcreditcardsテーブルにデータを保存できるようにした
#why
クレジット決済ができるようにするため
=> signup-pay.jp-registration

app/assets/stylesheets/products/_new.scss, app/views/products/new.html.haml
#What
商品出品ページのviewの作成。
#Why
本アプリケーションにおいて必須画面(view)なため。
=> new_product_add_commit

app/controllers/products_controller.rb, app/models/product.rb, app/views/products/new.html.haml, config/routes.rb, db/migrate/20191013070636_change_datatype_buyer_id_of_products.rb, db/schema.rb
#What
products.controllerにて、商品のデータが保存される機能の実装。
createアクションの追加。
#Why
本アプリケーションにとって商品の登録機能は根幹機能となるため。
=> products_function

app/assets/stylesheets/users/_preview.scss, app/views/users/preview.html.haml
#what
preview画面修正
#why
class名が被っていたため修正
=> class-edit

app/models/streetaddress.rb, app/models/user.rb, db/migrate/20191013065514_change_data_phone_number_to_streetaddresses.rb, db/schema.rb
=> validation-implementation

app/assets/stylesheets/devise/registrations/_signup.scss, app/controllers/signups_controller.rb, app/controllers/streetaddresses_controller.rb, app/views/signups/user1.html.haml, app/views/streetaddresses/new.html.haml, config/routes.rb
=> error-message

app/controllers/products_controller.rb, app/models/image.rb, app/models/product.rb, app/views/products/new.html.haml, db/migrate/20191013074229_create_images.rb, db/schema.rb
#What
商品出品ページの画像を保存できる機能の追加。
複数テーブルの保存。
#Why
本アプリケーションにとって必要機能であるため。
=> img_function

app/controllers/products_controller.rb, config/routes.rb
#What
routes.rbにbuy_confirmationのルーティングを追加。
#Why
購入確認ページを作成するため。
=> routes_add

app/assets/javascripts/category.js, app/assets/stylesheets/_header.scss, app/assets/stylesheets/products/_index.scss, app/controllers/application_controller.rb, app/controllers/categories_controller.rb, app/controllers/products_controller.rb, app/models/category.rb, app/models/product_category.rb, app/views/categories/get_category_children.json.jbuilder, app/views/categories/get_category_grandchildren.json.jbuilder, app/views/categories/window.html.haml, app/views/layouts/_header.html.haml, app/views/products/index.html.haml, config/routes.rb, db/migrate/20191014051841_create_product_categories.rb, db/schema.rb
- categoryのテーブルの作成（ancestryを使用）
- product_categoryテーブルの作成(中間テーブル)
- ドロップダウンリストの作成
https://gyazo.com/00c8268771128d703f7fda3188fe8496
- カテゴリーによる商品の絞り込みを可能にするため。
=> カテゴリー機能の実装

app/assets/javascripts/category.js, app/assets/stylesheets/_header.scss, app/views/layouts/_header.html.haml
=> edit_js_droplist

config/routes.rb
#what
productsに編集と削除のルーティング追加
#why
メルカリ実装に必要なため
=> products-add

app/assets/stylesheets/_header.scss, app/assets/stylesheets/users/_show.scss, app/controllers/products_controller.rb, app/views/categories/window.html.haml, app/views/layouts/_header.html.haml, app/views/users/show.html.haml
- headerのリンクをログイン状態とそうでないとで条件わけ
- link先を指定
- 効率向上のため
=> edit_user-link

app/controllers/products_controller.rb, config/routes.rb
#what
商品の削除、編集機能実装
#why
メルカリ機能にて必要なため
=> edit-delete-create

app/assets/stylesheets/application.scss, app/assets/stylesheets/categories/index.scss, app/assets/stylesheets/products/_banner.scss, app/controllers/categories_controller.rb, app/views/categories/index.html.haml, app/views/layouts/_banner.html.haml, app/views/layouts/_header.html.haml, app/views/products/index.html.haml
- categoriea/indexの作成
- カテゴリーを一覧表示しそこから商品を絞り込めるようにするため
=> coregory_inde_view

app/assets/stylesheets/users/_mail_password.scss, app/views/users/mail_password.html.haml
メール、パスワードを変更するviewの実装。
メールとパスワードを変更できるようにする為。
=> mail-password-view-edit

app/views/users/logout.html.haml, db/schema.rb
ログアウトのview実装。
ログアウトができるようにする為。
https://gyazo.com/84d3fac37b2ba0cd501d9745d54c09b5
=> logout-view

app/assets/stylesheets/_header.scss, app/assets/stylesheets/_nav.scss, app/assets/stylesheets/application.scss, app/views/categories/index.html.haml, app/views/layouts/_nav.html.haml, app/views/products/index.html.haml, app/views/users/_side-bar.html.haml, app/views/users/logout.html.haml, app/views/users/show.html.haml, config/breadcrumbs.rb, config/routes.rb, db/schema.rb
- パンくずリストのhtml,scssを設定
https://gyazo.com/0aa171534a16c1195bbf47c5dfeb30da
- 各ページにてパンくずリストを実装するため
=> carate_pankuzulist

app/assets/stylesheets/devise/registrations/_new.scss, app/assets/stylesheets/devise/registrations/_signup_footer.scss, app/views/creditcards/pay.html.haml, app/views/devise/sessions/new.html.haml, app/views/signups/user1.html.haml, app/views/signups/user2.html.haml
ログイン/新規登録のview実装
ログイン/新規登録する為
【ログインページ】
https://gyazo.com/1b79bcf6a112918680295ce2b2532444
【新規登録ページ】
https://gyazo.com/389eecb0b4a1a60deb9a8697fdb2480a
https://gyazo.com/c9ec384ded7891eceb7ac5a1a617f01d
https://gyazo.com/2cd7da8173982f522a71041d29af2daa
https://gyazo.com/ad76508cbf8a7d7a7fd02bb54511750a
https://gyazo.com/d6f2051f61f2026c0d4a5eb192138d04
https://gyazo.com/4411c20b729d5224ad690f4a5c1b5c04
=> login-signup-view

app/views/signups/user1.html.haml
=> user1-edit

app/assets/javascripts/user.js, app/controllers/users_controller.rb, app/views/users/_notification-list.html.haml, app/views/users/_side-bar.html.haml, app/views/users/_todo-list.html.haml, app/views/users/edit.html.haml, app/views/users/mail_password.html.haml, app/views/users/preview.html.haml, app/views/users/show.html.haml, app/views/users/sms_confirmation.html.haml, config/breadcrumbs.rb
- パンくずリストを各ビューに追加
- user/showのjsを追加
- 本物のメルカリに近づけるため
=> edit_pankuzu_edit_js

app/models/product.rb, spec/controllers/products_controller_spec.rb, spec/factories/products.rb
#what
単体テストコード編集
#why
メルカリ実装時に必要なため
=> test-code-edit

Gemfile, Gemfile.lock, app/assets/javascripts/payjp.js, app/assets/stylesheets/devise/registrations/_signup.scss, app/controllers/creditcards_controller.rb, app/controllers/signups_controller.rb, app/views/devise/sessions/new.html.haml, app/views/layouts/application.html.haml, app/views/signups/user1.html.haml, config/application.rb, config/initializers/recaptcha.rb, config/locales/ja.yml
#what
・JSファイルにてENV環境変数を使える様に変更
・reCAPTCHAの導入
#why
・APIKEYが漏れない様にした
・BOT対策
=> js-env-edit

.gitignore, app/models/image.rb, app/uploaders/image_uploader.rb, app/views/products/index.html.haml, app/views/products/show.html.haml, config/initializers/carrierwave.rb
#what
ローカルでは画像がS3に保存されないよう設定
#why
メルカリ機能に必要なため
=> local-create

app/assets/stylesheets/products/_index.scss, app/assets/stylesheets/products/_show.scss, app/controllers/products_controller.rb, app/views/products/index.html.haml, app/views/products/show.html.haml
- 売却済みの商品にsold-outバッジを追加
- 売却済みの商品を購入不可に
- 商品購入の重複を防ぐため
=> sold-out-btn

app/assets/stylesheets/_header.scss, app/controllers/products_controller.rb, app/views/layouts/_header.html.haml, app/views/products/search.html.haml
=> incrementalsearch-products

app/assets/stylesheets/products/_banner.scss, app/controllers/categories_controller.rb, app/views/categories/index.html.haml, app/views/categories/show.html.haml, config/breadcrumbs.rb
- カテゴリーによる絞り込み画面でのパンくずリストを作成
- カテゴリーの階層によってパンくずの表示内容が変わるため。
=> edit_catgory-show-pankuzu

db/migrate/20191023120505_delete_name_id_uniq_index_from_products.rb, db/schema.rb
=> migrate-edit

app/views/layouts/_display_btn.html.haml, app/views/products/show.html.haml
・購入・出品・編集・削除ボタンのコード修正
・ユーザーがサインイン済みと済みでないときに挙動を追加
=> rifakutarinngu

app/assets/javascripts/product.js, app/assets/stylesheets/products/_new.scss, app/controllers/products_controller.rb, app/views/products/edit.html.haml, app/views/products/new.html.haml
#What
products/editの画像編集機能の実装
product.jsに追加
#Why
商品の編集ページにて画像の編集を出来るようにするため。
=> product_edit_js

app/assets/javascripts/animation.js, app/assets/javascripts/application.js, app/assets/javascripts/category.js, app/assets/javascripts/image.js, app/assets/javascripts/product.js, app/assets/javascripts/search.js, app/assets/javascripts/slider.js, app/assets/javascripts/user.js
ブラウザバックをするとjsのイベントに影響していたので、jsのturbolinks:loadを消しました
=> turbolinks-edit

app/controllers/products_controller.rb, app/views/products/edit.html.haml
=> controller-edit

spec/factories/images.rb, spec/models/image_spec.rb
#What
imagesテーブルの単体テストコード追加。
#Why
本アプリケーションのimagesテーブル使用時にバグが出ないように確認するため。
=> test_code_add

app/assets/javascripts/product.js, app/controllers/products_controller.rb, app/views/products/get_size.json.jbuilder, app/views/products/new.html.haml, config/routes.rb
- product/newにてサイズのセレクトフォームを追加
- 商品にサイズを持たせるため
=> edit_newproduct_sizeselect

app/assets/javascripts/product.js, app/assets/stylesheets/products/_new.scss, app/controllers/products_controller.rb, app/models/product.rb, app/views/products/get_brand.json.jbuilder, app/views/products/new.html.haml
- product/newにてブランド選択を追加
- ブランドによる商品の絞り込みを可能にするため
=> edit_product/new_brand

app/controllers/products_controller.rb, app/models/searchsize.rb, app/models/searchsize_size.rb, app/models/size.rb, app/views/products/search.html.haml, db/migrate/20191028104501_create_searchsizes.rb, db/migrate/20191028111615_create_searchsize_sizes.rb, db/schema.rb, db/seeds.rb
#what
商品詳細検索機能(商品サイズデータ)実装
※作業中
#why
メルカリ機能に必要なため
=> data-create

app/assets/stylesheets/products/_show.scss, app/controllers/products_controller.rb, app/models/product.rb, app/models/user.rb, app/views/products/edit.html.haml, app/views/products/show.html.haml
- product/showにてリンク先の設定
- ユーザーのその他の商品や、ブランドのその他の商品をデータベースから取得
- product/editにて手数料の初期値を表示
- 完成度を上げるため
=> edit_product/show

app/assets/stylesheets/products/_search.scss, app/views/products/index.html.haml
=> edit_product_index
